### ISSUE TITLE
cant find configuration directory

### ISSUE THREAD

**Issue by pickeld** [CoalaJoe/person_component#1]
hey there, 
ive been waiting for a long time to someone to make it possible to manage users under hass
unfortunately i cant find the "{YOUR_HOME_ASSISTANT_CONFIGURATION}/custom_components/."
directory. 
do i need to create it?
do i need to install specific version of hass?
thanks!

**Comment by robmarkcole** [comment]
Yes you need to create it. See 

https://home-assistant.io/developers/creating_components/

Cheers
